syntax = "proto3";

package aiload;

import "core.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/descriptor.proto";
import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";

option cc_enable_arenas = true;
option go_package = "/aiload";

service aiload {


	// @gen: user
	// @model: ModelUser
	// @action: add
	rpc AddUserAdmin (AddUserAdminReq) returns (AddUserAdminRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "AddUserAdmin",
		};
		option (lazygophers.lrpc.core.lazygen) = {
			role: "admin",
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: get
	rpc GetUser (GetUserReq) returns (GetUserRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "GetUser",
		};
		option (lazygophers.lrpc.core.lazygen) = {
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: get
	rpc GetUserAdmin (GetUserAdminReq) returns (GetUserAdminRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "GetUserAdmin",
		};
		option (lazygophers.lrpc.core.lazygen) = {
			role: "admin",
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: list
	rpc ListUserAdmin (ListUserAdminReq) returns (ListUserAdminRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "ListUserAdmin",
		};
		option (lazygophers.lrpc.core.lazygen) = {
			role: "admin",
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: set
	rpc SetUser (SetUserReq) returns (SetUserRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "SetUser",
		};
		option (lazygophers.lrpc.core.lazygen) = {
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: set
	rpc SetUserAdmin (SetUserAdminReq) returns (SetUserAdminRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "SetUserAdmin",
		};
		option (lazygophers.lrpc.core.lazygen) = {
			role: "admin",
		};
	};

	// @gen: user
	// @model: ModelUser
	// @action: del
	rpc DelUserAdmin (DelUserAdminReq) returns (DelUserAdminRsp) {
		option (lazygophers.lrpc.core.http) = {
			method: "POST",
			path: "DelUserAdmin",
		};
		option (lazygophers.lrpc.core.lazygen) = {
			role: "admin",
		};
	};

}

enum ErrCode {
	Success = 0;
}

enum Platform {
	Nil = 0;
	OpenAI = 1;
}

message ModelChannel {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// @gorm: index: idx_channel,unique
	int64 deleted_at = 4;

	string name = 5;
	// @gorm: index: idx_channel,unique
	string token = 6;
	// @gorm: index: idx_channel,unique
	Platform platform = 7;
}

message ModelChannelAccess {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// @gorm: index: idx_channel_access,unique
	int64 deleted_at = 4;

	// @gorm: index: idx_channel_access,unique
	uint64 channel_id = 5;
	// @gorm: index: idx_channel_access,unique
	string model = 6;
}

message ModelModelAlias {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// gorm: index:idx_alias,unique
	int64 deleted_at = 4;

	// gorm: index:idx_alias,unique
	string model = 5;
	// gorm: index:idx_alias,unique
	string model_alias = 6;
}

message ModelUser {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// gorm: index:idx_user,unique
	int64 deleted_at = 4;

	// gorm: index:idx_user,unique
	string username = 5;
	string password = 6;
	string name = 7;
}

message ModelUserToken {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// gorm: index:idx_token,unique
	int64 deleted_at = 4;

	// gorm: index:idx_token,unique
	uint64 user_id = 5;

	// gorm: index:idx_token,unique
	string token = 6;
	int64 limit = 7;
}

message ModelUserAccess {
	uint64 id = 1;
	int64 created_at = 2;
	int64 updated_at = 3;
	// @gorm: index:idx_user_access,unique
	int64 deleted_at = 4;
	// @gorm: index:idx_user_access,unique
	uint64 token = 5;
	// @gorm: index:idx_user_access,unique
	string model = 6;
}

message AddUserAdminReq {
	// @validate: required
	ModelUser user = 1;
}

message AddUserAdminRsp {
	ModelUser user = 1;
}

message GetUserReq {

}

message GetUserRsp {
	ModelUser user = 1;
}

message GetUserAdminReq {
	// @validate: required
	uint64 id = 1;
}

message GetUserAdminRsp {
	ModelUser user = 1;
}

message ListUserAdminReq {
	enum ListOption {
		ListOptionNil = 0;
		// @type: like
		ListOptionName = 1;
		// @type: like
		ListOptionUsername = 2;
	}

	// @validate: required
	lazygophers.lrpc.core.ListOption list_option = 1;
}

message ListUserAdminRsp {
	lazygophers.lrpc.core.Paginate paginate = 1;
	repeated ModelUser list = 2;
}

message SetUserReq {
	// @validate: required
	ModelUser user = 1;
}

message SetUserRsp {
	ModelUser user = 1;
}

message SetUserAdminReq {
	// @validate: required
	ModelUser user = 1;
}

message SetUserAdminRsp {
	ModelUser user = 1;
}

message DelUserAdminReq {
	// @validate: required
	uint64 id = 1;
}

message DelUserAdminRsp {
}
