// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// 	codegen	v0.0.0-SNAPSHOT-5c1b1b5
// 	go		go1.24.5
// source: aiload.proto

package aiload

import (
	_ "github.com/lazygophers/lrpc/middleware/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Success ErrCode = 0
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "Success",
	}
	ErrCode_value = map[string]int32{
		"Success": 0,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_aiload_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_aiload_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{0}
}

type Platform int32

const (
	Platform_Nil    Platform = 0
	Platform_OpenAI Platform = 1
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "Nil",
		1: "OpenAI",
	}
	Platform_value = map[string]int32{
		"Nil":    0,
		"OpenAI": 1,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_aiload_proto_enumTypes[1].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_aiload_proto_enumTypes[1]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{1}
}

type ModelChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"column:id;primaryKey;PRIMARY KEY;autoIncrement;AUTOINCREMENT"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" toml:"created_at,omitempty" gorm:"autoCreateTime;column:created_at;not null;default:0"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" toml:"updated_at,omitempty" gorm:"default:0;autoUpdateTime;column:updated_at;not null" yaml:"updated_at,omitempty"`
	// @gorm: index: idx_channel,unique
	DeletedAt int64  `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"not null;default:0;index:idx_channel,unique;column:deleted_at" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty"`
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" gorm:"type:varchar(255);not null;default:'';column:name" yaml:"name,omitempty" toml:"name,omitempty"`
	// @gorm: index: idx_channel,unique
	Token string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty" gorm:"default:'';column:token;index:idx_channel,unique;type:varchar(255);not null" yaml:"token,omitempty" toml:"token,omitempty"`
	// @gorm: index: idx_channel,unique
	Platform Platform `protobuf:"varint,7,opt,name=platform,proto3,enum=aiload.Platform" json:"platform,omitempty" gorm:"column:platform;index:idx_channel,unique;not null;default:0" yaml:"platform,omitempty" toml:"platform,omitempty"`
}

func (x *ModelChannel) Reset() {
	*x = ModelChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChannel) ProtoMessage() {}

func (x *ModelChannel) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChannel.ProtoReflect.Descriptor instead.
func (*ModelChannel) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{0}
}

func (x *ModelChannel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelChannel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelChannel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelChannel) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelChannel) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ModelChannel) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_Nil
}

type ModelChannelAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"AUTOINCREMENT;column:id;primaryKey;PRIMARY KEY;autoIncrement"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"autoCreateTime;column:created_at;not null;default:0" yaml:"created_at,omitempty" toml:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" yaml:"updated_at,omitempty" toml:"updated_at,omitempty" gorm:"column:updated_at;not null;default:0;autoUpdateTime"`
	// @gorm: index: idx_channel_access,unique
	DeletedAt int64 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"column:deleted_at;not null;default:0;index:idx_channel_access,unique" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty"`
	// @gorm: index: idx_channel_access,unique
	ChannelId uint64 `protobuf:"varint,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty" gorm:"column:channel_id;index:idx_channel_access,unique;not null;default:0" yaml:"channel_id,omitempty" toml:"channel_id,omitempty"`
	// @gorm: index: idx_channel_access,unique
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty" gorm:"index:idx_channel_access,unique;type:varchar(255);not null;default:'';column:model" yaml:"model,omitempty" toml:"model,omitempty"`
}

func (x *ModelChannelAccess) Reset() {
	*x = ModelChannelAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelChannelAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChannelAccess) ProtoMessage() {}

func (x *ModelChannelAccess) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChannelAccess.ProtoReflect.Descriptor instead.
func (*ModelChannelAccess) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{1}
}

func (x *ModelChannelAccess) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelChannelAccess) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelChannelAccess) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelChannelAccess) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelChannelAccess) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ModelChannelAccess) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ModelModelAlias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"column:id;primaryKey;PRIMARY KEY;autoIncrement;AUTOINCREMENT"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" toml:"created_at,omitempty" gorm:"autoCreateTime;column:created_at;not null;default:0"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" yaml:"updated_at,omitempty" toml:"updated_at,omitempty" gorm:"column:updated_at;not null;default:0;autoUpdateTime"`
	// gorm: index:idx_alias,unique
	DeletedAt int64 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty" gorm:"default:0;column:deleted_at;not null"`
	// gorm: index:idx_alias,unique
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty" yaml:"model,omitempty" toml:"model,omitempty" gorm:"type:varchar(255);not null;default:'';column:model"`
	// gorm: index:idx_alias,unique
	ModelAlias string `protobuf:"bytes,6,opt,name=model_alias,json=modelAlias,proto3" json:"model_alias,omitempty" toml:"model_alias,omitempty" gorm:"type:varchar(255);not null;default:'';column:model_alias" yaml:"model_alias,omitempty"`
}

func (x *ModelModelAlias) Reset() {
	*x = ModelModelAlias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelModelAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelModelAlias) ProtoMessage() {}

func (x *ModelModelAlias) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelModelAlias.ProtoReflect.Descriptor instead.
func (*ModelModelAlias) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{2}
}

func (x *ModelModelAlias) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelModelAlias) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelModelAlias) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelModelAlias) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelModelAlias) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelModelAlias) GetModelAlias() string {
	if x != nil {
		return x.ModelAlias
	}
	return ""
}

type ModelUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"column:id;primaryKey;PRIMARY KEY;autoIncrement;AUTOINCREMENT"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" toml:"created_at,omitempty" gorm:"column:created_at;not null;default:0;autoCreateTime"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" yaml:"updated_at,omitempty" toml:"updated_at,omitempty" gorm:"autoUpdateTime;column:updated_at;not null;default:0"`
	// gorm: index:idx_user,unique
	DeletedAt int64 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty" gorm:"column:deleted_at;not null;default:0"`
	// gorm: index:idx_user,unique
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty" yaml:"username,omitempty" toml:"username,omitempty" gorm:"type:varchar(255);not null;default:'';column:username"`
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty" yaml:"password,omitempty" toml:"password,omitempty" gorm:"default:'';column:password;type:varchar(255);not null"`
}

func (x *ModelUser) Reset() {
	*x = ModelUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUser) ProtoMessage() {}

func (x *ModelUser) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUser.ProtoReflect.Descriptor instead.
func (*ModelUser) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{3}
}

func (x *ModelUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelUser) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelUser) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelUser) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ModelUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ModelUserToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"autoIncrement;AUTOINCREMENT;column:id;primaryKey;PRIMARY KEY"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" toml:"created_at,omitempty" gorm:"autoCreateTime;column:created_at;not null;default:0"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" yaml:"updated_at,omitempty" toml:"updated_at,omitempty" gorm:"autoUpdateTime;column:updated_at;not null;default:0"`
	// gorm: index:idx_token,unique
	DeletedAt int64 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty" gorm:"column:deleted_at;not null;default:0"`
	// gorm: index:idx_token,unique
	UserId uint64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" yaml:"user_id,omitempty" toml:"user_id,omitempty" gorm:"not null;default:0;column:user_id"`
	// gorm: index:idx_token,unique
	Token string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty" yaml:"token,omitempty" toml:"token,omitempty" gorm:"column:token;type:varchar(255);not null;default:''"`
	Limit int64  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty" yaml:"limit,omitempty" toml:"limit,omitempty" gorm:"not null;default:0;column:limit"`
}

func (x *ModelUserToken) Reset() {
	*x = ModelUserToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUserToken) ProtoMessage() {}

func (x *ModelUserToken) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUserToken.ProtoReflect.Descriptor instead.
func (*ModelUserToken) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{4}
}

func (x *ModelUserToken) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelUserToken) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelUserToken) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelUserToken) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelUserToken) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelUserToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ModelUserToken) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ModelUserAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id,omitempty" toml:"id,omitempty" gorm:"column:id;primaryKey;PRIMARY KEY;autoIncrement;AUTOINCREMENT"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" yaml:"created_at,omitempty" toml:"created_at,omitempty" gorm:"default:0;autoCreateTime;column:created_at;not null"`
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"autoUpdateTime;column:updated_at;not null;default:0" yaml:"updated_at,omitempty" toml:"updated_at,omitempty"`
	// @gorm: index:idx_user_access,unique
	DeletedAt int64 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"index:idx_user_access,unique;column:deleted_at;not null;default:0" yaml:"deleted_at,omitempty" toml:"deleted_at,omitempty"`
	// @gorm: index:idx_user_access,unique
	Token uint64 `protobuf:"varint,5,opt,name=token,proto3" json:"token,omitempty" yaml:"token,omitempty" toml:"token,omitempty" gorm:"column:token;index:idx_user_access,unique;not null;default:0"`
	// @gorm: index:idx_user_access,unique
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty" gorm:"index:idx_user_access,unique;type:varchar(255);not null;default:'';column:model" yaml:"model,omitempty" toml:"model,omitempty"`
}

func (x *ModelUserAccess) Reset() {
	*x = ModelUserAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUserAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUserAccess) ProtoMessage() {}

func (x *ModelUserAccess) ProtoReflect() protoreflect.Message {
	mi := &file_aiload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUserAccess.ProtoReflect.Descriptor instead.
func (*ModelUserAccess) Descriptor() ([]byte, []int) {
	return file_aiload_proto_rawDescGZIP(), []int{5}
}

func (x *ModelUserAccess) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelUserAccess) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelUserAccess) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelUserAccess) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelUserAccess) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *ModelUserAccess) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_aiload_proto protoreflect.FileDescriptor

var file_aiload_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x69, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x69, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd3, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x69, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22,
	0xb5, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xc2, 0x01, 0x0a, 0x0e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0xaa, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2a, 0x16, 0x0a, 0x07,
	0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x2a, 0x1f, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x07, 0x0a, 0x03, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x70, 0x65,
	0x6e, 0x41, 0x49, 0x10, 0x01, 0x32, 0x08, 0x0a, 0x06, 0x61, 0x69, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x0c, 0x5a, 0x07, 0x2f, 0x61, 0x69, 0x6c, 0x6f, 0x61, 0x64, 0xf8, 0x01, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aiload_proto_rawDescOnce sync.Once
	file_aiload_proto_rawDescData = file_aiload_proto_rawDesc
)

func file_aiload_proto_rawDescGZIP() []byte {
	file_aiload_proto_rawDescOnce.Do(func() {
		file_aiload_proto_rawDescData = protoimpl.X.CompressGZIP(file_aiload_proto_rawDescData)
	})
	return file_aiload_proto_rawDescData
}

var file_aiload_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aiload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aiload_proto_goTypes = []any{
	(ErrCode)(0),               // 0: aiload.ErrCode
	(Platform)(0),              // 1: aiload.Platform
	(*ModelChannel)(nil),       // 2: aiload.ModelChannel
	(*ModelChannelAccess)(nil), // 3: aiload.ModelChannelAccess
	(*ModelModelAlias)(nil),    // 4: aiload.ModelModelAlias
	(*ModelUser)(nil),          // 5: aiload.ModelUser
	(*ModelUserToken)(nil),     // 6: aiload.ModelUserToken
	(*ModelUserAccess)(nil),    // 7: aiload.ModelUserAccess
}
var file_aiload_proto_depIdxs = []int32{
	1, // 0: aiload.ModelChannel.platform:type_name -> aiload.Platform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aiload_proto_init() }
func file_aiload_proto_init() {
	if File_aiload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aiload_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ModelChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiload_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ModelChannelAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiload_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ModelModelAlias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiload_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModelUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiload_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ModelUserToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiload_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ModelUserAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aiload_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aiload_proto_goTypes,
		DependencyIndexes: file_aiload_proto_depIdxs,
		EnumInfos:         file_aiload_proto_enumTypes,
		MessageInfos:      file_aiload_proto_msgTypes,
	}.Build()
	File_aiload_proto = out.File
	file_aiload_proto_rawDesc = nil
	file_aiload_proto_goTypes = nil
	file_aiload_proto_depIdxs = nil
}
