// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-5c1b1b5
//		go		go1.24.5
//	update:	1753783305
//	source: aiload.proto

package aiload


import (
	"database/sql/driver"
	"github.com/lazygophers/utils"
)

func (m *ModelChannel) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelChannel) Value() (driver.Value, error) {
	return utils.Value(m)
}

func (m *ModelChannelAccess) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelChannelAccess) Value() (driver.Value, error) {
	return utils.Value(m)
}

func (m *ModelModelAlias) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelModelAlias) Value() (driver.Value, error) {
	return utils.Value(m)
}

func (m *ModelUser) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelUser) Value() (driver.Value, error) {
	return utils.Value(m)
}

func (m *ModelUserAccess) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelUserAccess) Value() (driver.Value, error) {
	return utils.Value(m)
}

func (m *ModelUserToken) Scan(value interface{}) error {
	return utils.Scan(m, value)
}

func (m *ModelUserToken) Value() (driver.Value, error) {
	return utils.Value(m)
}


