// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-35b9c92
//		go		go1.24.5
//	update:	1753797444
//	source: aiload.proto

package aiload

func (ModelUserAccess) TableName() string {
	return "aiload_user_access"
}
func (ModelChannel) TableName() string {
	return "aiload_channel"
}
func (ModelChannelAccess) TableName() string {
	return "aiload_channel_access"
}
func (ModelModelAlias) TableName() string {
	return "aiload_model_alias"
}
func (ModelUser) TableName() string {
	return "aiload_user"
}
func (ModelUserToken) TableName() string {
	return "aiload_user_token"
}

