// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-35b9c92
//		go		go1.24.5
//	update:	1755398321
//	source: aiload.proto

package main

import (
	"github.com/lazygophers/aiload"
	"github.com/lazygophers/aiload/internal/api"
	"github.com/lazygophers/aiload/internal/impl"
)

var Routes = []*api.Route{
	{
		Method:  "POST",
		Path:    aiload.RpcPathAddUserAdmin,
		Handler: impl.ToHandler(impl.AddUserAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathGetUser,
		Handler: impl.ToHandler(impl.GetUser, "user"),
		Role:    "public",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathGetUserAdmin,
		Handler: impl.ToHandler(impl.GetUserAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathListUserAdmin,
		Handler: impl.ToHandler(impl.ListUserAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathSetUser,
		Handler: impl.ToHandler(impl.SetUser, "user"),
		Role:    "public",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathSetUserAdmin,
		Handler: impl.ToHandler(impl.SetUserAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathDelUserAdmin,
		Handler: impl.ToHandler(impl.DelUserAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathLogin,
		Handler: impl.ToHandler(impl.Login, "public"),
		Role:    "public",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathSetChannelAdmin,
		Handler: impl.ToHandler(impl.SetChannelAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathDelChannelAdmin,
		Handler: impl.ToHandler(impl.DelChannelAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathAddChannelAdmin,
		Handler: impl.ToHandler(impl.AddChannelAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathGetChannelAdmin,
		Handler: impl.ToHandler(impl.GetChannelAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathListChannelAdmin,
		Handler: impl.ToHandler(impl.ListChannelAdmin, "admin"),
		Role:    "admin",
	},
	{
		Method:  "POST",
		Path:    aiload.RpcPathGetModelListAdmin,
		Handler: impl.ToHandler(impl.GetModelListAdmin, "admin"),
		Role:    "admin",
	},
}
